config/routes.rb
Rails.application.routes.draw do
  resources :players do
    collection do
      get 'report'
      get 'exceptions'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
  before_save do
    self.match_name = full_name.parameterize
  end

  scope :current, -> { where(current: true) }

  def self.default_scope
    order :full_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/report
  def report
    @version = Player.maximum(:updated_at).to_i
    @players = Player.current # .limit(5)
  end

  # GET /players/exceptions
  def exceptions
    @fields = %i(
      allergic medication photo_gumshield photo_no_gumshield tetanus school
      gp_name gp_address
      pog1_name pog1_phone1
    )

    where_clause = (['date_of_birth'] | @fields.map(&:to_s)).join(' IS NULL OR ') + ' IS NULL'

    @version = Player.maximum(:updated_at).to_i
    @players = Player.current.where(where_clause) # .limit(5)
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:full_name, :date_of_birth, :allergic, :medication, :photo_gumshield, :photo_no_gumshield)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
  def image_or_message(image_id, message)
    if image_id
      cl_image_tag("#{image_id}.jpg", :width => 300, :height => 450, :crop => :fill)
    else
      content_tag :div, class: 'photo-replacement' do
        content_tag :span, class: 'exception' do
          message
        end
      end
    end
  end

  def field_or_box(value)
    return value unless value.nil?
    content_tag :span, class: 'missing-data' do
      "\xa0"
    end
  end

  def datetime_or_box(value)
    value ? l(value, format: '%d %B %Y') : field_or_box(value)
  end

  def standard_footer
    content_tag :footer do
      l last_updated, format: 'Last updated at %H:%m on %d %B %Y'
    end
  end

  def last_updated
    @last_updated ||= Player.maximum(:updated_at)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= ENV['APP_NAME'] %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/_form.html.erb
<%= form_for(player) do |f| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :full_name %>
    <%= f.text_field :full_name %>
  </div>

  <div class="field">
    <%= f.label :date_of_birth %>
    <%= f.datetime_select :date_of_birth %>
  </div>

  <div class="field">
    <%= f.label :allergic %>
    <%= f.check_box :allergic %>
  </div>

  <div class="field">
    <%= f.label :medication %>
    <%= f.check_box :medication %>
  </div>

  <div class="field">
    <%= f.label :photo_gumshield %>
    <%= f.text_field :photo_gumshield %>
  </div>

  <div class="field">
    <%= f.label :photo_no_gumshield %>
    <%= f.text_field :photo_no_gumshield %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/exceptions.html.erb
<h3><%= ENV['APP_NAME'] %> - missing information</h3>

<table class="missing-data">
  <thead>
    <tr>
      <th>Player</th>
      <th>Date of birth</th>

      <% @fields.each do |field| %>
        <th><%= field.to_s.humanize %></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= field_or_box player.full_name %></td>
        <td><%= datetime_or_box(player.date_of_birth) %></td>

        <% @fields.each do |field| %>
          <td><div><%= field_or_box player.send(field) %></div></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= standard_footer %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Players</h1>

<table>
  <thead>
    <tr>
      <th>Full name</th>
      <th>Date of birth</th>
      <th>Allergic</th>
      <th>Medication</th>
      <th>Photo gumshield</th>
      <th>Photo no gumshield</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.full_name %></td>
        <td><%= player.date_of_birth %></td>
        <td><%= player.allergic %></td>
        <td><%= player.medication %></td>
        <td><%= player.photo_gumshield %></td>
        <td><%= player.photo_no_gumshield %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Back', players_path %>

app/views/players/report.html.erb
<% @players.each do |player| %>
<article class="page-break">
  <h1 class="display-5"><%= player.full_name %></h1>

  <div class="photos">
    <%= image_or_message player.photo_no_gumshield, 'Photo without gumshield needed' %>
    <%= image_or_message player.photo_gumshield, 'Photo with gumshield needed' %>
  </div>

  <table class="table">
    <tbody>
      <tr>
        <td class="label">Date of birth</td>
        <td>
          <% if player.date_of_birth %>
            <%= l(player.date_of_birth, format: '%d %B %Y') %>
          <% else %>
            <span class="exception">Unknown</span>
          <% end %>
        </td>
      </tr>

      <tr>
        <td class="label">Is the player allergic to any medication?</td>
        <td>
          <% if player.allergic %>
            <%= player.allergy_note || 'Yes' %>
          <% elsif player.allergic.nil? %>
            <span class="exception">Unknown</span>
          <% else %>
            No
          <% end %>
        </td>
      </tr>

      <tr>
        <td class="label">Is the player taking any prescribed medication?</td>
        <td>
          <% if player.medication %>
            <%= player.medication_note || 'Yes' %>
          <% elsif player.medication.nil? %>
            <span class="exception">Unknown</span>
          <% else %>
            No
          <% end %>
        </td>
      </tr>

      <tr>
        <td class="label">Year of latest tetanus inoculation</td>
        <td>
          <% if player.tetanus %>
            <%= player.tetanus %>
          <% else %>
            <span class="exception">Unknown</span>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>

  <table class="table">
    <tbody>
      <tr class="row">
        <td class = "col-4"><div class="contact">
          <label>Parent or guardian</label>
          <%= simple_format [player.pog1_name, player.pog1_phone1, player.pog1_phone2, player.pog1_address].compact.join("\n") %>
          <% if player.pog1_name.blank? || player.pog1_phone1.blank? %>
            <span class="exception">Parent or guardian's name and phone number needed</span>
          <% end %>
        </div></td>

        <td class = "col-4"><div class="contact">
          <label>Parent or guardian</label>
          <%= simple_format [player.pog2_name, player.pog2_phone1, player.pog2_phone2, player.pog2_address].compact.join("\n") %>
        </div></td>

        <td class = "col-4"><div class="contact">
          <label>Other emergency contact</label>
          <%= simple_format [player.ec_name, player.ec_phone1, player.ec_phone2].compact.join("\n") %>
        </div></td>
      </tr>

      <tr class="row">
        <td class = "col-4"><div class="contact">
          <label>GP</label>
          <%= simple_format [player.gp_name, player.gp_address].compact.join("\n") %>
          <% if player.gp_name.blank? || player.gp_address.blank? %>
            <span class="exception">GP's name and address needed</span>
          <% end %>
        </div></td>

        <td class = "col-4"><div class="contact">
          <label>School</label>
          <%= player.school %>
          <% if player.school.blank? %>
            <span class="exception">School name needed</span>
          <% end %>
        </div></td>
      </tr>
    </tbody>
  </table>
</article>

<%= standard_footer %>
<% end %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Full name:</strong>
  <%= @player.full_name %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @player.date_of_birth %>
</p>

<p>
  <strong>Allergic:</strong>
  <%= @player.allergic %>
</p>

<p>
  <strong>Medication:</strong>
  <%= @player.medication %>
</p>

<p>
  <strong>Photo gumshield:</strong>
  <%= @player.photo_gumshield %>
</p>

<p>
  <strong>Photo no gumshield:</strong>
  <%= @player.photo_no_gumshield %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>